export interface Catalog {
  id: number;
  name: string;
  color: string;
}

export interface PeriodicElement {
  id: number;
  symbol: string;
  name: string;
  row: number;
  column: number;
  catalog: number;
  weights: string;
}

export const catalogs: Catalog[] = [
  {
    id: 0,
    name: 'Hydrogen-specific',
    color: '#2a4165',
  },
  {
    id: 1,
    name: 'Alkali metal',
    color: '#244d57',
  },
  {
    id: 2,
    name: 'Alkaline earth metal',
    color: '#622e39',
  },
  {
    id: 3,
    name: 'Transition metal',
    color: '#433c65',
  },
  {
    id: 4,
    name: 'Post-transition metal',
    color: '#2f4d47',
  },
  {
    id: 5,
    name: 'Metalloid',
    color: '#523e1b',
  },
  {
    id: 6,
    name: 'Nonmetal',
    color: '#2a4165',
  },
  {
    id: 7,
    name: 'Halogen',
    color: '#2a4165',
  },
  {
    id: 8,
    name: 'Noble gas',
    color: '#623842',
  },
  {
    id: 9,
    name: 'Lanthanide',
    color: '#004a77',
  },
  {
    id: 10,
    name: 'Actinide',
    color: '#613b28',
  },
  {
    id: 11,
    name: 'Unknown properties',
    color: '#46474c',
  },
];

export const periodicElements: PeriodicElement[] = [
  {
    id: 1,
    symbol: 'H',
    name: 'Hydrogen',
    row: 0,
    column: 0,
    catalog: 0,
    weights: '1.008',
  },
  {
    id: 2,
    symbol: 'He',
    name: 'Helium',
    row: 0,
    column: 17,
    catalog: 8,
    weights: '4.0026',
  },
  {
    id: 3,
    symbol: 'Li',
    name: 'Lithium',
    row: 1,
    column: 0,
    catalog: 1,
    weights: '6.94',
  },
  {
    id: 4,
    symbol: 'Be',
    name: 'Beryllium',
    row: 1,
    column: 1,
    catalog: 2,
    weights: '9.0122',
  },
  {
    id: 5,
    symbol: 'B',
    name: 'Boron',
    row: 1,
    column: 12,
    catalog: 5,
    weights: '10.81',
  },
  {
    id: 6,
    symbol: 'C',
    name: 'Carbon',
    row: 1,
    column: 13,
    catalog: 6,
    weights: '12.011',
  },
  {
    id: 7,
    symbol: 'N',
    name: 'Nitrogen',
    row: 1,
    column: 14,
    catalog: 6,
    weights: '14.007',
  },
  {
    id: 8,
    symbol: 'O',
    name: 'Oxygen',
    row: 1,
    column: 15,
    catalog: 6,
    weights: '15.999',
  },
  {
    id: 9,
    symbol: 'F',
    name: 'Fluorine',
    row: 1,
    column: 16,
    catalog: 7,
    weights: '18.998',
  },
  {
    id: 10,
    symbol: 'Ne',
    name: 'Neon',
    row: 1,
    column: 17,
    catalog: 8,
    weights: '20.18',
  },
  {
    id: 11,
    symbol: 'Na',
    name: 'Sodium',
    row: 2,
    column: 0,
    catalog: 1,
    weights: '22.99',
  },
  {
    id: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    row: 2,
    column: 1,
    catalog: 2,
    weights: '24.305',
  },
  {
    id: 13,
    symbol: 'Al',
    name: 'Aluminium',
    row: 2,
    column: 12,
    catalog: 4,
    weights: '26.982',
  },
  {
    id: 14,
    symbol: 'Si',
    name: 'Silicon',
    row: 2,
    column: 13,
    catalog: 5,
    weights: '28.085',
  },
  {
    id: 15,
    symbol: 'P',
    name: 'Phosphorus',
    row: 2,
    column: 14,
    catalog: 6,
    weights: '30.974',
  },
  {
    id: 16,
    symbol: 'S',
    name: 'Sulfur',
    row: 2,
    column: 15,
    catalog: 6,
    weights: '32.06',
  },
  {
    id: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    row: 2,
    column: 16,
    catalog: 7,
    weights: '35.45',
  },
  {
    id: 18,
    symbol: 'Ar',
    name: 'Argon',
    row: 2,
    column: 17,
    catalog: 8,
    weights: '39.948',
  },
  {
    id: 19,
    symbol: 'K',
    name: 'Potassium',
    row: 3,
    column: 0,
    catalog: 1,
    weights: '39.098',
  },
  {
    id: 20,
    symbol: 'Ca',
    name: 'Calcium',
    row: 3,
    column: 1,
    catalog: 2,
    weights: '40.078',
  },
  {
    id: 21,
    symbol: 'Sc',
    name: 'Scandium',
    row: 3,
    column: 2,
    catalog: 3,
    weights: '44.956',
  },
  {
    id: 22,
    symbol: 'Ti',
    name: 'Titanium',
    row: 3,
    column: 3,
    catalog: 3,
    weights: '47.867',
  },
  {
    id: 23,
    symbol: 'V',
    name: 'Vanadium',
    row: 3,
    column: 4,
    catalog: 3,
    weights: '50.942',
  },
  {
    id: 24,
    symbol: 'Cr',
    name: 'Chromium',
    row: 3,
    column: 5,
    catalog: 3,
    weights: '51.996',
  },
  {
    id: 25,
    symbol: 'Mn',
    name: 'Manganese',
    row: 3,
    column: 6,
    catalog: 3,
    weights: '54.938',
  },
  {
    id: 26,
    symbol: 'Fe',
    name: 'Iron',
    row: 3,
    column: 7,
    catalog: 3,
    weights: '55.845',
  },
  {
    id: 27,
    symbol: 'Co',
    name: 'Cobalt',
    row: 3,
    column: 8,
    catalog: 3,
    weights: '58.933',
  },
  {
    id: 28,
    symbol: 'Ni',
    name: 'Nickel',
    row: 3,
    column: 9,
    catalog: 3,
    weights: '58.693',
  },
  {
    id: 29,
    symbol: 'Cu',
    name: 'Copper',
    row: 3,
    column: 10,
    catalog: 3,
    weights: '63.546',
  },
  {
    id: 30,
    symbol: 'Zn',
    name: 'Zinc',
    row: 3,
    column: 11,
    catalog: 3,
    weights: '65.38',
  },
  {
    id: 31,
    symbol: 'Ga',
    name: 'Gallium',
    row: 3,
    column: 12,
    catalog: 4,
    weights: '69.723',
  },
  {
    id: 32,
    symbol: 'Ge',
    name: 'Germanium',
    row: 3,
    column: 13,
    catalog: 5,
    weights: '72.63',
  },
  {
    id: 33,
    symbol: 'As',
    name: 'Arsenic',
    row: 3,
    column: 14,
    catalog: 5,
    weights: '74.922',
  },
  {
    id: 34,
    symbol: 'Se',
    name: 'Selenium',
    row: 3,
    column: 15,
    catalog: 6,
    weights: '78.971',
  },
  {
    id: 35,
    symbol: 'Br',
    name: 'Bromine',
    row: 3,
    column: 16,
    catalog: 7,
    weights: '79.904',
  },
  {
    id: 36,
    symbol: 'Kr',
    name: 'Krypton',
    row: 3,
    column: 17,
    catalog: 8,
    weights: '83.798',
  },
  {
    id: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    row: 4,
    column: 0,
    catalog: 1,
    weights: '85.468',
  },
  {
    id: 38,
    symbol: 'Sr',
    name: 'Strontium',
    row: 4,
    column: 1,
    catalog: 2,
    weights: '87.62',
  },
  {
    id: 39,
    symbol: 'Y',
    name: 'Yttrium',
    row: 4,
    column: 2,
    catalog: 3,
    weights: '88.906',
  },
  {
    id: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    row: 4,
    column: 3,
    catalog: 3,
    weights: '91.224',
  },
  {
    id: 41,
    symbol: 'Nb',
    name: 'Niobium',
    row: 4,
    column: 4,
    catalog: 3,
    weights: '92.906',
  },
  {
    id: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    row: 4,
    column: 5,
    catalog: 3,
    weights: '95.95',
  },
  {
    id: 43,
    symbol: 'Tc',
    name: 'Technetium',
    row: 4,
    column: 6,
    catalog: 3,
    weights: '98.0',
  },
  {
    id: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    row: 4,
    column: 7,
    catalog: 3,
    weights: '101.07',
  },
  {
    id: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    row: 4,
    column: 8,
    catalog: 3,
    weights: '102.91',
  },
  {
    id: 46,
    symbol: 'Pd',
    name: 'Palladium',
    row: 4,
    column: 9,
    catalog: 3,
    weights: '106.42',
  },
  {
    id: 47,
    symbol: 'Ag',
    name: 'Silver',
    row: 4,
    column: 10,
    catalog: 3,
    weights: '107.87',
  },
  {
    id: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    row: 4,
    column: 11,
    catalog: 3,
    weights: '112.41',
  },
  {
    id: 49,
    symbol: 'In',
    name: 'Indium',
    row: 4,
    column: 12,
    catalog: 4,
    weights: '114.82',
  },
  {
    id: 50,
    symbol: 'Sn',
    name: 'Tin',
    row: 4,
    column: 13,
    catalog: 4,
    weights: '118.71',
  },
  {
    id: 51,
    symbol: 'Sb',
    name: 'Antimony',
    row: 4,
    column: 14,
    catalog: 5,
    weights: '121.76',
  },
  {
    id: 52,
    symbol: 'Te',
    name: 'Tellurium',
    row: 4,
    column: 15,
    catalog: 5,
    weights: '127.6',
  },
  {
    id: 53,
    symbol: 'I',
    name: 'Iodine',
    row: 4,
    column: 16,
    catalog: 7,
    weights: '126.9',
  },
  {
    id: 54,
    symbol: 'Xe',
    name: 'Xenon',
    row: 4,
    column: 17,
    catalog: 8,
    weights: '131.29',
  },
  {
    id: 55,
    symbol: 'Cs',
    name: 'Cesium',
    row: 5,
    column: 0,
    catalog: 1,
    weights: '132.91',
  },
  {
    id: 56,
    symbol: 'Ba',
    name: 'Barium',
    row: 5,
    column: 1,
    catalog: 2,
    weights: '137.33',
  },
  {
    id: 57,
    symbol: 'La',
    name: 'Lanthanum',
    row: 5,
    column: 2,
    catalog: 9,
    weights: '138.91',
  },
  {
    id: 58,
    symbol: 'Ce',
    name: 'Cerium',
    row: 7,
    column: 3,
    catalog: 9,
    weights: '140.12',
  },
  {
    id: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    row: 7,
    column: 4,
    catalog: 9,
    weights: '140.91',
  },
  {
    id: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    row: 7,
    column: 5,
    catalog: 9,
    weights: '144.24',
  },
  {
    id: 61,
    symbol: 'Pm',
    name: 'Promethium',
    row: 7,
    column: 6,
    catalog: 9,
    weights: '145.0',
  },
  {
    id: 62,
    symbol: 'Sm',
    name: 'Samarium',
    row: 7,
    column: 7,
    catalog: 9,
    weights: '150.36',
  },
  {
    id: 63,
    symbol: 'Eu',
    name: 'Europium',
    row: 7,
    column: 8,
    catalog: 9,
    weights: '151.96',
  },
  {
    id: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    row: 7,
    column: 9,
    catalog: 9,
    weights: '157.25',
  },
  {
    id: 65,
    symbol: 'Tb',
    name: 'Terbium',
    row: 7,
    column: 10,
    catalog: 9,
    weights: '158.93',
  },
  {
    id: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    row: 7,
    column: 11,
    catalog: 9,
    weights: '162.5',
  },
  {
    id: 67,
    symbol: 'Ho',
    name: 'Holmium',
    row: 7,
    column: 12,
    catalog: 9,
    weights: '164.93',
  },
  {
    id: 68,
    symbol: 'Er',
    name: 'Erbium',
    row: 7,
    column: 13,
    catalog: 9,
    weights: '167.26',
  },
  {
    id: 69,
    symbol: 'Tm',
    name: 'Thulium',
    row: 7,
    column: 14,
    catalog: 9,
    weights: '168.93',
  },
  {
    id: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    row: 7,
    column: 15,
    catalog: 9,
    weights: '173.04',
  },
  {
    id: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    row: 7,
    column: 16,
    catalog: 9,
    weights: '174.97',
  },
  {
    id: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    row: 5,
    column: 3,
    catalog: 3,
    weights: '178.49',
  },
  {
    id: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    row: 5,
    column: 4,
    catalog: 3,
    weights: '180.95',
  },
  {
    id: 74,
    symbol: 'W',
    name: 'Tungsten',
    row: 5,
    column: 5,
    catalog: 3,
    weights: '183.84',
  },
  {
    id: 75,
    symbol: 'Re',
    name: 'Rhenium',
    row: 5,
    column: 6,
    catalog: 3,
    weights: '186.21',
  },
  {
    id: 76,
    symbol: 'Os',
    name: 'Osmium',
    row: 5,
    column: 7,
    catalog: 3,
    weights: '190.23',
  },
  {
    id: 77,
    symbol: 'Ir',
    name: 'Iridium',
    row: 5,
    column: 8,
    catalog: 3,
    weights: '192.22',
  },
  {
    id: 78,
    symbol: 'Pt',
    name: 'Platinum',
    row: 5,
    column: 9,
    catalog: 3,
    weights: '195.08',
  },
  {
    id: 79,
    symbol: 'Au',
    name: 'Gold',
    row: 5,
    column: 10,
    catalog: 3,
    weights: '196.97',
  },
  {
    id: 80,
    symbol: 'Hg',
    name: 'Mercury',
    row: 5,
    column: 11,
    catalog: 3,
    weights: '200.59',
  },
  {
    id: 81,
    symbol: 'Tl',
    name: 'Thallium',
    row: 5,
    column: 12,
    catalog: 4,
    weights: '204.38',
  },
  {
    id: 82,
    symbol: 'Pb',
    name: 'Lead',
    row: 5,
    column: 13,
    catalog: 4,
    weights: '207.2',
  },
  {
    id: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    row: 5,
    column: 14,
    catalog: 4,
    weights: '208.98',
  },
  {
    id: 84,
    symbol: 'Po',
    name: 'Polonium',
    row: 5,
    column: 15,
    catalog: 4,
    weights: '209.0',
  },
  {
    id: 85,
    symbol: 'At',
    name: 'Astatine',
    row: 5,
    column: 16,
    catalog: 4,
    weights: '210.0',
  },
  {
    id: 86,
    symbol: 'Rn',
    name: 'Radon',
    row: 5,
    column: 17,
    catalog: 8,
    weights: '222.0',
  },
  {
    id: 87,
    symbol: 'Fr',
    name: 'Francium',
    row: 6,
    column: 0,
    catalog: 1,
    weights: '223.0',
  },
  {
    id: 88,
    symbol: 'Ra',
    name: 'Radium',
    row: 6,
    column: 1,
    catalog: 2,
    weights: '226.0',
  },
  {
    id: 89,
    symbol: 'Ac',
    name: 'Actinium',
    row: 6,
    column: 2,
    catalog: 10,
    weights: '227.0',
  },
  {
    id: 90,
    symbol: 'Th',
    name: 'Thorium',
    row: 8,
    column: 3,
    catalog: 10,
    weights: '232.04',
  },
  {
    id: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    row: 8,
    column: 4,
    catalog: 10,
    weights: '231.04',
  },
  {
    id: 92,
    symbol: 'U',
    name: 'Uranium',
    row: 8,
    column: 5,
    catalog: 10,
    weights: '238.03',
  },
  {
    id: 93,
    symbol: 'Np',
    name: 'Neptunium',
    row: 8,
    column: 6,
    catalog: 10,
    weights: '237.0',
  },
  {
    id: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    row: 8,
    column: 7,
    catalog: 10,
    weights: '244.0',
  },
  {
    id: 95,
    symbol: 'Am',
    name: 'Americium',
    row: 8,
    column: 8,
    catalog: 10,
    weights: '243.0',
  },
  {
    id: 96,
    symbol: 'Cm',
    name: 'Curium',
    row: 8,
    column: 9,
    catalog: 10,
    weights: '247.0',
  },
  {
    id: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    row: 8,
    column: 10,
    catalog: 10,
    weights: '247.0',
  },
  {
    id: 98,
    symbol: 'Cf',
    name: 'Californium',
    row: 8,
    column: 11,
    catalog: 10,
    weights: '251.0',
  },
  {
    id: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    row: 8,
    column: 12,
    catalog: 10,
    weights: '252.0',
  },
  {
    id: 100,
    symbol: 'Fm',
    name: 'Fermium',
    row: 8,
    column: 13,
    catalog: 10,
    weights: '257.0',
  },
  {
    id: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    row: 8,
    column: 14,
    catalog: 10,
    weights: '258.0',
  },
  {
    id: 102,
    symbol: 'No',
    name: 'Nobelium',
    row: 8,
    column: 15,
    catalog: 10,
    weights: '259.0',
  },
  {
    id: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    row: 8,
    column: 16,
    catalog: 10,
    weights: '262.0',
  },
  {
    id: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    row: 6,
    column: 3,
    catalog: 3,
    weights: '267.0',
  },
  {
    id: 105,
    symbol: 'Db',
    name: 'Dubnium',
    row: 6,
    column: 4,
    catalog: 3,
    weights: '270.0',
  },
  {
    id: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    row: 6,
    column: 5,
    catalog: 3,
    weights: '271.0',
  },
  {
    id: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    row: 6,
    column: 6,
    catalog: 3,
    weights: '270.0',
  },
  {
    id: 108,
    symbol: 'Hs',
    name: 'Hassium',
    row: 6,
    column: 7,
    catalog: 3,
    weights: '277.0',
  },
  {
    id: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    row: 6,
    column: 8,
    catalog: 11,
    weights: '276.0',
  },
  {
    id: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    row: 6,
    column: 9,
    catalog: 11,
    weights: '281.0',
  },
  {
    id: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    row: 6,
    column: 10,
    catalog: 11,
    weights: '282.0',
  },
  {
    id: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    row: 6,
    column: 11,
    catalog: 11,
    weights: '285.0',
  },
  {
    id: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    row: 6,
    column: 12,
    catalog: 11,
    weights: '286.0',
  },
  {
    id: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    row: 6,
    column: 13,
    catalog: 11,
    weights: '289.0',
  },
  {
    id: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    row: 6,
    column: 14,
    catalog: 11,
    weights: '290.0',
  },
  {
    id: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    row: 6,
    column: 15,
    catalog: 11,
    weights: '293.0',
  },
  {
    id: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    row: 6,
    column: 16,
    catalog: 11,
    weights: '294.0',
  },
  {
    id: 118,
    symbol: 'Og',
    name: 'Oganesson',
    row: 6,
    column: 17,
    catalog: 11,
    weights: '294.0',
  },
];
